export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_RECCOMENDED_PRODUCTS:"SET_RECCOMENDED_PRODUCTS",
    SET_FRUITS:"SET_FRUITS",
    SET_VEGETABLES:"SET_VEGETABLES",
    SET_FOODGRAINS:"SET_FOODGRAINS",

    SET_FRUITS_BUTTON:"SET_FRUITS_BUTTON",
    SET_VEGETABLES_BUTTON:"SET_VEGETABLES_BUTTON",
    SET_FOODGRAINS_BUTTON:"SET_FOODGRAINS_BUTTON",
    CLEAR_FILTERS:"CLEAR_FILTERS",

    SET_STATIONERY:"SET_STATIONERY",
    REMOVE_FILTER:"REMOVE_FILTER",
}